<!DOCTYPE html>
<html>
<head>
    <title>Activity Logs Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; }
        .subtitle { font-size: 14px; color: #666; }
        .search-info { margin-bottom: 15px; }
        .table { width: 100%; border-collapse: collapse; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; }
        .table th { background-color: #f2f2f2; text-align: left; }
        .table tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 30px; font-size: 12px; text-align: right; }
        .badge { padding: 2px 6px; border-radius: 4px; font-size: 12px; }
        .badge-old { background-color: #fee2e2; color: #b91c1c; }
        .badge-new { background-color: #dcfce7; color: #166534; }
        .arrow { color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Activity Logs Report</div>
        <div class="subtitle">Generated on: {{ $currentDate }}</div>
    </div>

    @if($searchTerm)
        <div class="search-info">
            <strong>Search Term:</strong> {{ $searchTerm }}
        </div>
    @endif

    <div class="summary">
        <strong>Total Activities:</strong> {{ $totalActivities }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Action</th>
                <th>User</th>
                <th>Changes</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($activities as $activity)
            <tr>
                <td>{{ ucfirst($activity->log_name) }}</td>
                <td>{{ ucfirst($activity->description) }}</td>
                <td>{{ $activity->causer ? $activity->causer->first_name.' '.$activity->causer->last_name : 'System' }}</td>
                <td>
                    @foreach($activity->formatted_properties as $property)
                        <div style="margin-bottom: 5px;">
                            <strong>{{ $property['field'] }}:</strong>
                            @if($activity->description === 'updated')
                                <span class="badge badge-old">{{ $property['old'] ?? '(empty)' }}</span>
                                <span class="arrow">→</span>
                                <span class="badge badge-new">{{ $property['new'] ?? '(empty)' }}</span>
                            @elseif($activity->description === 'created')
                                <span class="badge badge-new">{{ $property['new'] ?? '(empty)' }}</span>
                            @elseif($activity->description === 'deleted')
                                <span class="badge badge-old">{{ $property['old'] ?? '(empty)' }}</span>
                            @else
                                {{ is_array($property['value']) ? json_encode($property['value']) : ($property['value'] ?? '(empty)') }}
                            @endif
                        </div>
                    @endforeach
                </td>
                <td>{{ $activity->created_at->format('M j, Y g:i A') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Report generated by {{ config('app.name') }}
    </div>
</body>
</html>