<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Logs Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header .subtitle {
            color: #666;
            font-size: 14px;
        }
        .filters {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
        .filters p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #4f46e5;
            color: white;
            font-weight: bold;
        }
        table tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .status-login {
            color: #059669;
            font-weight: bold;
        }
        .status-logout {
            color: #2563eb;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .summary {
            background-color: #e0e7ff;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>User Login Logs Report</h1>
        <div class="subtitle">Generated on: {{ $currentDate }}</div>
    </div>

    @if($searchTerm)
    <div class="filters">
        <p><strong>Search Filter:</strong> {{ $searchTerm }}</p>
    </div>
    @endif

    <div class="summary">
        Total Records: {{ $totalLogs }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Event Type</th>
                <th>User</th>
                <th>Email</th>
                <th>IP Address</th>
                <th>Timestamp</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $index => $log)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>
                    <span class="@if($log->description == 'user_login') status-login @else status-logout @endif">
                        {{ $log->description == 'user_login' ? 'LOGIN' : 'LOGOUT' }}
                    </span>
                </td>
                <td>
                    @if($log->causer)
                        {{ $log->causer->first_name }} {{ $log->causer->last_name }}
                    @else
                        System generated
                    @endif
                </td>
                <td>
                    @if($log->causer)
                        {{ $log->causer->email }}
                    @else
                        N/A
                    @endif
                </td>
                <td>
                    @php
                        $ipAddress = 'N/A';
                        if (!empty($log->formatted_properties)) {
                            foreach ($log->formatted_properties as $property) {
                                if ($property['field'] === 'IP Address') {
                                    $ipAddress = $property['value'];
                                    break;
                                }
                            }
                        }
                    @endphp
                    {{ $ipAddress }}
                </td>
                <td>{{ $log->created_at->format('M j, Y g:i A') }}</td>
                <td>{{ $log->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ config('app.name') }} on {{ $currentDate }}</p>
    </div>
</body>
</html>